config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :publications, only: [:index, :show]
  namespace :admin do
    resource :publications 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/publication.rb
class Publication < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/publications_controller.rb
class Admin::PublicationController < AdminController
  before_filter :find_publication, only:[:show, :edit, :update, :destroy]
  def index
    @publications = Publication.all
  end
  def show; end

  def new
    @publications = Publication.new
  end
  def create
    @publications =
    Publication.new (publication_params)

    if @publication.save
      redirect_to
      admin_publication_path(@publication)
    else
      render :edit, alert: "Something went wrong."
    end
  end

  private
  def find_publication
    @publication = Publication.find(param[:id])
  end

  def publication_params
    params.require(:publication).permit(:title,
    :description,
    :file_url)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :check_for_admin
  def check_for_admin
    if current_user.nil? || !current_user.is_admin
      redirect_to root_path, alert: "You must be an admin to acess this path."
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  def index
    @publications = Publication.all
  end
  
  def show
    @publication = Publication.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">SubscriptionApp</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li>
          <a href='#'> Signed in as <%= current_user.email %></a>
        </li>
        <li>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        </li>
        <% else %>
          <li>
            <%= link_to "Sign in", new_user_session_path %>
          </li>
          <li>
            <%= link_to "Sign up ", new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/index.html.erb
<h1>Subcription application <h1/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SubscriptionApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'nav' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/publications/index.html.erb
<h2>Publications</h2>
<% @publications.each do |publication| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel_title"><%= publication.title %></h3>
    </div>
    <div class="panel-body">
      <p><%= publication.description %></p>
      <%= publication.file_url %></p>
    </div>
    <div class="panel-footer">
    <%= link_to "View More Details", publication_path(publication), class:"btn btn-default" %>
    </div>
  </div>
  <% end %>

app/views/publications/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel_title"><%= @publication.title %></h3>
  </div>
  <div class="panel-body">
    <p><%= @publication.description %></p>
    <%= @publication.file_url %></p>
  </div>
</div>